from eth2deposit.utils.crypto import PBKDF2 as PBKDF2, SHA256 as SHA256
from typing import Optional, Sequence, Tuple

def get_seed(mnemonic: str, password: str) -> bytes: ...
def get_languages(path: str) -> Tuple[str, ...]: ...
def determine_mnemonic_language(mnemonic: str, words_path: str) -> Sequence[str]: ...
def verify_mnemonic(mnemonic: str, words_path: str) -> bool: ...
def get_mnemonic(language: str, words_path: str, *, entropy: Optional[bytes]=...) -> str: ...
