from eth2deposit.cli.existing_mnemonic import existing_mnemonic as existing_mnemonic
from eth2deposit.cli.new_mnemonic import new_mnemonic as new_mnemonic

def check_python_version() -> None: ...
def cli() -> None: ...
