from typing import Any

ZERO_BYTES32: Any
DOMAIN_DEPOSIT: Any
BLS_WITHDRAWAL_PREFIX: Any
ETH2GWEI: Any
MIN_DEPOSIT_AMOUNT: Any
MAX_DEPOSIT_AMOUNT: Any
WORD_LISTS_PATH: Any
DEFAULT_VALIDATOR_KEYS_FOLDER_NAME: str
UNICODE_CONTROL_CHARS: Any
