from typing import Any

def SHA256(x: bytes) -> bytes: ...
def scrypt(password: str, salt: str, n: int, r: int, p: int, dklen: int) -> bytes: ...
def PBKDF2(password: bytes, salt: bytes, dklen: int, c: int, prf: str) -> bytes: ...
def HKDF(salt: bytes, IKM: bytes, L: int, *, info: bytes=...) -> bytes: ...
def AES_128_CTR(key: bytes, iv: bytes) -> Any: ...
