from eth2deposit.utils.constants import DOMAIN_DEPOSIT as DOMAIN_DEPOSIT, ZERO_BYTES32 as ZERO_BYTES32
from ssz import Serializable
from typing import Any

bytes8: Any

class SigningData(Serializable):
    fields: Any = ...

class ForkData(Serializable):
    fields: Any = ...

def compute_deposit_domain(fork_version: bytes) -> bytes: ...
def compute_deposit_fork_data_root(current_version: bytes) -> bytes: ...
def compute_signing_root(ssz_object: Serializable, domain: bytes) -> bytes: ...

class DepositMessage(Serializable):
    fields: Any = ...

class DepositData(Serializable):
    fields: Any = ...
