from eth2deposit.exceptions import ValidationError as ValidationError
from eth2deposit.utils.constants import MAX_DEPOSIT_AMOUNT as MAX_DEPOSIT_AMOUNT, MIN_DEPOSIT_AMOUNT as MIN_DEPOSIT_AMOUNT
from eth2deposit.utils.ssz import DepositData as DepositData, DepositMessage as DepositMessage, compute_deposit_domain as compute_deposit_domain, compute_signing_root as compute_signing_root
from typing import Any, Dict

def verify_deposit_data_json(filefolder: str) -> bool: ...
def validate_deposit(deposit_data_dict: Dict[str, Any]) -> bool: ...
def validate_password_strength(password: str) -> None: ...
